# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newview.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 900)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VolUp = QtWidgets.QPushButton(self.centralwidget)
        self.VolUp.setGeometry(QtCore.QRect(50, 300, 93, 28))
        self.VolUp.setObjectName("VolUp")
        self.power = QtWidgets.QPushButton(self.centralwidget)
        self.power.setGeometry(QtCore.QRect(250, 17, 93, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.power.setFont(font)
        self.power.setObjectName("power")
        self.ChanUp = QtWidgets.QPushButton(self.centralwidget)
        self.ChanUp.setGeometry(QtCore.QRect(450, 300, 93, 28))
        self.ChanUp.setObjectName("ChanUp")
        self.VolDown = QtWidgets.QPushButton(self.centralwidget)
        self.VolDown.setGeometry(QtCore.QRect(50, 400, 93, 28))
        self.VolDown.setObjectName("VolDown")
        self.ChanDown = QtWidgets.QPushButton(self.centralwidget)
        self.ChanDown.setGeometry(QtCore.QRect(450, 400, 93, 28))
        self.ChanDown.setObjectName("ChanDown")
        self.Mute = QtWidgets.QPushButton(self.centralwidget)
        self.Mute.setGeometry(QtCore.QRect(50, 650, 93, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Mute.setFont(font)
        self.Mute.setObjectName("Mute")
        self.Pause = QtWidgets.QPushButton(self.centralwidget)
        self.Pause.setGeometry(QtCore.QRect(450, 650, 93, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pause.setFont(font)
        self.Pause.setObjectName("Pause")
        self.Status = QtWidgets.QGraphicsView(self.centralwidget)
        self.Status.setGeometry(QtCore.QRect(170, 90, 256, 192))
        self.Status.setObjectName("Status")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(45, 340, 104, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(445, 340, 104, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit_2.setAutoFillBackground(False)
        self.plainTextEdit_2.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit_2.setCenterOnScroll(False)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.volumetext = QtWidgets.QTextEdit(self.centralwidget)
        self.volumetext.setGeometry(QtCore.QRect(190, 510, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.volumetext.setFont(font)
        self.volumetext.setObjectName("volumetext")
        self.volumedisplay = QtWidgets.QLabel(self.centralwidget)
        self.volumedisplay.setGeometry(QtCore.QRect(310, 490, 55, 61))
        self.volumedisplay.setObjectName("volumedisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tv Remote"))
        self.VolUp.setText(_translate("MainWindow", "+"))
        self.power.setText(_translate("MainWindow", "Power"))
        self.ChanUp.setText(_translate("MainWindow", "+"))
        self.VolDown.setText(_translate("MainWindow", "-"))
        self.ChanDown.setText(_translate("MainWindow", "-"))
        self.Mute.setText(_translate("MainWindow", "Pause"))
        self.Pause.setText(_translate("MainWindow", "Mute"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "   Volume"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "  Channel"))
        self.volumetext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; font-weight:400;\">Volume =</span></p></body></html>"))
        self.volumedisplay.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
